-- Database initialization script for Zoom Platform Microservice
-- This script sets up the database with proper permissions and initial data

-- Create extensions if they don't exist
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- Create additional indexes for performance
CREATE INDEX IF NOT EXISTS idx_extractor_configs_job_type_platform ON extractor_configs(job_type_id, platform_id);
CREATE INDEX IF NOT EXISTS idx_loader_configs_job_type_platform ON loader_configs(job_type_id, platform_id);
CREATE INDEX IF NOT EXISTS idx_transformer_registry_job_type ON transformer_registry(job_type_id);
CREATE INDEX IF NOT EXISTS idx_job_type_configs_source_target ON job_type_configs(source_platform_id, target_platform_id);

-- Create composite indexes for common queries
CREATE INDEX IF NOT EXISTS idx_extractor_configs_default_lookup ON extractor_configs(job_type_id, platform_id, is_default) WHERE is_default = true;
CREATE INDEX IF NOT EXISTS idx_loader_configs_default_lookup ON loader_configs(job_type_id, platform_id, is_default) WHERE is_default = true;
CREATE INDEX IF NOT EXISTS idx_transformer_registry_active_default ON transformer_registry(job_type_id, is_active, is_default) WHERE is_active = true;

-- Add comments to tables for documentation
COMMENT ON TABLE extractor_configs IS 'Registry for storing extraction plans generated by the LLM. Mirrors ExtractorRegistry from main ETL system.';
COMMENT ON TABLE loader_configs IS 'Registry for storing loading plans generated by the LLM. Mirrors LoaderRegistry from main ETL system.';
COMMENT ON TABLE transformer_registry IS 'Registry for storing transformation configurations (formerly SSOT schemas). Mirrors SSOTSchema from main ETL system.';
COMMENT ON TABLE job_type_configs IS 'Represents types of ETL jobs that can be performed. Mirrors JobType from main ETL system.';

-- Log initialization
INSERT INTO pg_stat_statements_info (dealloc) VALUES (0) ON CONFLICT DO NOTHING;

-- Set up database for optimal performance
ALTER DATABASE zoom_microservice SET shared_preload_libraries = 'pg_stat_statements';
ALTER DATABASE zoom_microservice SET log_statement = 'none';
ALTER DATABASE zoom_microservice SET log_duration = off;
ALTER DATABASE zoom_microservice SET log_min_duration_statement = 1000;